server:
  port: 2333
  address: 127.0.0.1
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    gcWarning: true
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    ratelimit:
      ipBlocks: [] # list of ip blocks
      excludedIps: [] # ips which should be explicit excluded from usage by lavalink
      strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
